name: vimeo_player_flutter
description: Vimeo Player Flutter package for Flutter apps. Compatible with both iOS and Android platforms.
version: 0.0.3+1
homepage: https://github.com/prahack/vimeo_player

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
